name: License Check

on: [push, pull_request]

jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # oder Ihre gewünschte Ruby-Version

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run license_finder
        run: bundle exec license_finder
