name: License Check

on: [push, pull_request]

jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # oder Ihre gewünschte Ruby-Version

      - name: Install license_finder
        run: |
          gem install license_finder --user-install
          echo "GEM_HOME=$(ruby -e 'puts Gem.user_dir')" >> $GITHUB_ENV
          echo "PATH=$GEM_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Run license_finder
        run: license_finder
