name: License Check

on: [push, pull_request]

jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          gem install license_finder
          # Fügen Sie hier weitere Installationsbefehle für Ihre Projektabhängigkeiten hinzu
      - name: Run License Finder
        run: license_finder
