name: License Compliance Check

on: [push, pull_request]

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Checkout Compliance Script
        uses: actions/checkout@v4
        with:
          repository: Pelkowsk/TestMitGradle
          path: compliance-scripts

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install ScanCode
        run: pip install scancode-toolkit

      - name: Run ScanCode
        run: |
          scancode --license \
            --ignore "TestMitGradle/build/*" \
            --ignore "TestMitGradle/gradle/wrapper/*" \
            --ignore "TestMitGradle/.idea/*" \
            --ignore "TestMitGradle/*.iml" \
            --ignore "TestMitGradle/.gitignore" \
            --ignore "TestMitGradle/LICENSE" \
            --ignore "TestMitGradle/Dockerfile" \
            --ignore "TestMitGradle/.github/*" \
            --ignore "TestMitGradle/compliance-scripts/*" \
            --ignore "TestMitGradle/gen/*" \
            --ignore "TestMitGradle/gradle/*" \
            --ignore "TestMitGradle/src/test/*" \
            --json-pp scancode-results.json .


      - name: Check License Compliance
        run: python check_license_compliance.py

      - name: Upload ScanCode Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scancode-report
          path: scancode-results.json

      - name: Upload Compliance Check Result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: compliance-check-result
          path: compliance_check_result.txt
