name: License Compliance Check

on: [push, pull_request]

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Passen Sie die Version entsprechend Ihrem Projekt an

      - name: Install ScanCode
        run: |
          pip install scancode-toolkit

      - name: Run ScanCode
        run: |
          scancode --license --json-pp scancode-results.json .
